(cl:defpackage rl_msgs-msg
  (:use )
  (:export
   "<ACTION>"
   "ACTION"
   "<ACTIONSTAMPED>"
   "ACTIONSTAMPED"
   "<ENVDESCRIPTION>"
   "ENVDESCRIPTION"
   "<GOAL>"
   "GOAL"
   "<ODOMSTATEREWARD>"
   "ODOMSTATEREWARD"
   "<ODOMSTATEREWARDSTAMPED>"
   "ODOMSTATEREWARDSTAMPED"
   "<STATEREWARD>"
   "STATEREWARD"
   "<STATEREWARDSTAMPED>"
   "STATEREWARDSTAMPED"
  ))

