// Generated by gencpp from file vesc_msgs/VescCtrlStamped.msg
// DO NOT EDIT!


#ifndef VESC_MSGS_MESSAGE_VESCCTRLSTAMPED_H
#define VESC_MSGS_MESSAGE_VESCCTRLSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vesc_msgs/VescCtrl.h>

namespace vesc_msgs
{
template <class ContainerAllocator>
struct VescCtrlStamped_
{
  typedef VescCtrlStamped_<ContainerAllocator> Type;

  VescCtrlStamped_()
    : header()
    , control()  {
    }
  VescCtrlStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , control(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::vesc_msgs::VescCtrl_<ContainerAllocator>  _control_type;
  _control_type control;





  typedef boost::shared_ptr< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> const> ConstPtr;

}; // struct VescCtrlStamped_

typedef ::vesc_msgs::VescCtrlStamped_<std::allocator<void> > VescCtrlStamped;

typedef boost::shared_ptr< ::vesc_msgs::VescCtrlStamped > VescCtrlStampedPtr;
typedef boost::shared_ptr< ::vesc_msgs::VescCtrlStamped const> VescCtrlStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator1> & lhs, const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.control == rhs.control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator1> & lhs, const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vesc_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e17fcb1950b5483f670eede40f4b03a7";
  }

  static const char* value(const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe17fcb1950b5483fULL;
  static const uint64_t static_value2 = 0x670eede40f4b03a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vesc_msgs/VescCtrlStamped";
  }

  static const char* value(const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header  header\n"
"VescCtrl control\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vesc_msgs/VescCtrl\n"
"#commanded VESC duty cycle, current, brake current, speed, motor position, servo position\n"
"\n"
"int64 mode  #control mode 1-brake mode,2-current mode,3-speed mode,4-duty_cycle mode,5-position mode\n"
"float64 duty_cycle #vesc control mode\n"
"float64 current    #vesc control mode\n"
"float64 brake\n"
"float64 speed      #vesc control mode\n"
"float64 position\n"
"float64 servo\n"
;
  }

  static const char* value(const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VescCtrlStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vesc_msgs::VescCtrlStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vesc_msgs::VescCtrlStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "control: ";
    s << std::endl;
    Printer< ::vesc_msgs::VescCtrl_<ContainerAllocator> >::stream(s, indent + "  ", v.control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VESC_MSGS_MESSAGE_VESCCTRLSTAMPED_H
